[profile.default]
src = "src/audit"
test = "test"
libs = ["lib"]
solc = "0.8.27"
evm_version = "paris"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
